version: "3.9"

services:
  clean-dash:
    build:
      context: .
    image: clean-dash:$VERSION
    container_name: clean-dash
    ports:
      - "8084:8085"
    environment:
      - TARGET=$TARGET
    restart: unless-stopped